sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker-compose --version
    - uname -a
    - cat /etc/group
    - ls -al /var/run/docker.sock
    - whoami

script:
    - docker pull cyberdojofoundation/gcc_assert
    - docker pull cyberdojofoundation/ruby_mini_test
    - docker pull cyberdojofoundation/fsharp_nunit
    - ./build_and_test.sh

after_success:
    - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - docker push cyberdojo/runner:${DOCKER_ENGINE_VERSION}

